'use client'

import Link from 'next/link'
import { ArrowRight, BookOpen, Check, Headphones, Layers3, MessageSquareText, Mic2, Play, Trophy } from 'lucide-react'
import { AppShell, ScreenCard, ScreenHeading } from '@/components/layout/app-shell'

export default function HomePage() { return <AppShell title="Good morning, Remy"><div className="content-grid"><div className="main-column">
  <section className="hero-card"><div className="hero-copy"><div className="mini-label">✦ TODAY&apos;S GOAL</div><h2>One small step,<br /><em>big progress.</em></h2><p>Ten minutes is all it takes to keep your French moving forward.</p><Link href="/learn" className="primary-button">Start my session <ArrowRight size={17} /></Link></div><div className="hero-art" aria-hidden="true"><div className="art-sun" /><div className="art-building building-back" /><div className="art-building building-front" /><div className="art-roof" /><div className="art-window w1" /><div className="art-window w2" /><div className="art-plant" /><div className="art-table" /><div className="art-book" /></div></section>
  <section className="section-block"><ScreenHeading eyebrow="KEEP LEARNING" title="Pick up where you left off" action={<Link href="/learn" className="text-button">View all <ArrowRight size={15} /></Link>} /><div className="lesson-card"><div className="lesson-icon"><BookOpen size={25} /></div><div className="lesson-info"><div className="lesson-title-row"><strong>Daily life · Chapter 3</strong><span>65%</span></div><p>Morning routines</p><div className="progress-track"><span style={{ width: '65%' }} /></div><small>4 lessons remaining</small></div><Link href="/learn" className="circle-play" aria-label="Resume lesson"><Play size={17} fill="currentColor" /></Link></div></section>
  <section className="section-block"><ScreenHeading eyebrow="QUICK ACTIVITIES" title="Choose your practice" /><div className="activity-grid"><Link href="/reader" className="activity-card blue"><div className="activity-top"><div className="activity-icon"><Headphones size={21} /></div><span className="activity-time">5 MIN</span></div><strong>Listen & understand</strong><p>A mini story to listen to</p><span className="activity-arrow">→</span></Link><Link href="/speaking" className="activity-card pink"><div className="activity-top"><div className="activity-icon"><Mic2 size={21} /></div><span className="activity-time">3 MIN</span></div><strong>Speak out loud</strong><p>Practice 5 useful sentences</p><span className="activity-arrow">→</span></Link><Link href="/review" className="activity-card yellow"><div className="activity-top"><div className="activity-icon"><Layers3 size={21} /></div><span className="activity-time">7 MIN</span></div><strong>Review your words</strong><p>12 cards to revisit</p><span className="activity-arrow">→</span></Link><Link href="/handoff" className="activity-card blue"><div className="activity-top"><div className="activity-icon"><MessageSquareText size={21} /></div><span className="activity-time">2 MIN</span></div><strong>ChatGPT handoff</strong><p>Copy a ready-made prompt</p><span className="activity-arrow">→</span></Link></div></section>
</div><aside className="right-column"><ScreenCard><ScreenHeading eyebrow="THIS WEEK" title="Your consistency" /><div className="week-row">{['M','T','W','T','F','S','S'].map((day, i) => <div className={`day ${i === 5 ? 'today' : ''}`} key={`${day}-${i}`}><span>{day}</span><div className={i < 5 ? 'day-dot done' : 'day-dot'}>{i < 5 && <Check size={12} />}</div><small>{12 + i}</small></div>)}</div><div className="week-summary"><strong>5 days</strong><span>You are on a great streak.</span></div></ScreenCard><ScreenCard className="reading-card"><div className="reading-label"><BookOpen size={16} /> READING</div><h3>One Sunday in Lyon</h3><p>Read a short story and discover everyday vocabulary.</p><Link href="/reader" className="secondary-button">Read now <ArrowRight size={16} /></Link></ScreenCard><ScreenCard><div className="level-top"><div className="level-badge"><Trophy size={16} /></div><div><p className="eyebrow">YOUR LEVEL</p><h3>Intermediate</h3></div><span className="level-code">B1</span></div><p>180 XP until the next level.</p><div className="progress-track"><span style={{ width: '72%' }} /></div></ScreenCard></aside></div></AppShell> }
